name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Cache Coursier
        uses: actions/cache@v3
        with:
          path: ~/.coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Check Scala format
        run: sbt scalafmtCheckAll

      - name: Build project
        run: sbt compile

      - name: Run tests
        run: sbt test
